apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-secret-reader
subjects:
  - kind: ServiceAccount
    name: secure-operator
    namespace: default
roleRef:
  kind: ClusterRole
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-pods-viewer
subjects:
  - kind: ServiceAccount
    name: developer
    namespace: default
roleRef:
  kind: ClusterRole
  name: pods-viewer
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-pods-config
subjects:
  - kind: ServiceAccount
    name: devops
    namespace: default
roleRef:
  kind: ClusterRole
  name: pods-config
  apiGroup: rbac.authorization.k8s.io